name: Call a reusable workflow

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-workflow:
    uses: NNikitins/reusable-github-actions/.github/workflows/reusable-workflow.yml@main
    with:
      username: Nikita